- name: "HIGH | V-1073 | AUDIT | Systems must be maintained at a supported service pack level."
  win_command: reg query \"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\"
  register: supported_pack_level_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1073

- name: "HIGH | V-1073 | PATCH | Systems must be maintained at a supported service pack level."
  action: win_ping
  tags:
      - cat1
      - high
      - patch
      - V-1073

#May have to split into two tasks to check for both approved softwares
- name: "HIGH | V-1074 | AUDIT | An approved DoD antivirus program must be installed and used."
  win_command: reg query \"HKLM\SOFTWARE\Symantec\Symantec Endpoint Protection\SMC\" /v ProductVersion
  #reg query HKEY_LOCAL_MACHINE\Software\McAfee\DesktopProtection <- reg key missing value
  register: symantec_approved_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1074

- name: "HIGH | V-1074 | PATCH | An approved DoD antivirus program must be installed and used."
  action: win_ping
  tags:
      - cat1
      - high
      - patch
      - V-1074

- name: "HIGH | V-1093 | AUDIT | Anonymous enumeration of shares must be restricted."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v RestrictAnonymous
  register: anon_shares_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1093

- name: "HIGH | V-1093 | PATCH | Anonymous enumeration of shares must be restricted."
  win_regedit: 
    key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
    value: RestrictAnonymous
    data: 1
    datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1093

- name: "HIGH | V-1152 | AUDIT | Anonymous access to the registry must be restricted."
  win_command: reg query HKLM\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg
  register: anon_registry_access_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1152

# NOTE: V-1152 is shared between all OS's, but Backup Operators data for 2k12 is 'Read (This key only)' and for 2k8 is 'Special'.
- name: "HIGH | V-1152 | PATCH | Anonymous access to the registry must be restricted."
  win_regedit: 
    key: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg'
    value: "{{ item.value }}"
    data: "{{ item.data }}"
  with_items: 
     - { value: 'Administrators', data: 'Full' }
     - { value: 'Backup Operators', data: 'Read (This key only)' }
     - { value: 'LOCAL SERVICE', data: 'Read' }
  tags:
       - cat1
       - high
       - patch
       - V-1152

- name: "HIGH | V-1153 | AUDIT | The LanMan authentication level must be set to send NTLMv2 response only, and to refuse LM and NTLM."
  win_command: reg query HKLM\System\CurrentControlSet\Control\Lsa /v LMCompatibilityLevel
  register: lanMan_authentication_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1153

- name: "HIGH | V-1153 | PATCH | The LanMan authentication level must be set to send NTLMv2 response only, and to refuse LM and NTLM."
  win_regedit:
    key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
    value: LMCompatibilityLevel
    data: 5
    datatype: dword
  tags:
      - cat1
      - high
      - patch
      - V-1153

- name: "HIGH | V-1159 | AUDIT | The Recovery Console option must be set to prevent automatic logon to the system."
  win_command: reg query \"HKLM\Software\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\" /v SecurityLevel 
  register: recovery_prevent_autologin_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1159

- name: "HIGH | V-1159 | PATCH | The Recovery Console option must be set to prevent automatic logon to the system."
  win_regedit:
    key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\'
    value: SecurityLevel
    data: 0
    datatype: dword
  ignore_errors: yes
  tags:
      - cat1
      - high
      - patch
      - V-1159

#Not sure if this query needs to asses both type and data field, but indicated in STIG description
- name: "HIGH | V-2374 | AUDIT | Autoplay must be disabled for all drives."
  win_command: reg query HKLM\Software\Microsoft\Windows\CurrentVersion\policies\Explorer\ /v NoDriveTypeAutoRun /t REG_DWORD /f 25 
  register: autoplay_disabled_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-2374

- name: "HIGH | V-2374 | PATCH | Autoplay must be disabled for all drives."
  action: win_ping
  ignore_errors: yes
  tags:
      - cat1
      - high
      - patch
      - V-2374


- name: "HIGH | V-3339 | AUDIT | Unauthorized remotely accessible registry paths must not be configured."
  win_command: reg query \"HKLM\System\CurrentControlSet\Control\SecurePipeServers\ winreg\"
  register: remotely_accessible_registry_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-3339

- name: "HIGH | V-3339 | PATCH | Unauthorized remotely accessible registry paths must not be configured."
  win_regedit:
    key: 'HKLM:\System\CurrentControlSet\Control\SecurePipeServers\ winreg'
    state: absent
  ignore_errors: yes
  tags:
      - cat1
      - high
      - patch
      - V-3339

- name: "HIGH | V-3340 | AUDIT | Network shares that can be accessed anonymously must not be allowed."
  win_command: reg query HKLM\System\CurrentControlSet\Services\LanManServer\Parameters\ /v NullSessionShares
  register: network_shares_anonymous_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-3340

- name: "HIGH | V-3340 | PATCH | Network shares that can be accessed anonymously must not be allowed."
  action: win_ping
  ignore_errors: yes
  tags:
      - cat1
      - high
      - patch
      - V-3340

- name: "HIGH | V-3343 | AUDIT | Solicited Remote Assistance must not be allowed."
  win_command: reg query \"HKLM\Software\Policies\Microsoft\Windows NT\Terminal Services\" /v fAllowToGetHelp /t REG_DWORD /f 0
  register: solicited_remote_assistance_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-3343

- name: "HIGH | V-3343 | PATCH | Solicited Remote Assistance must not be allowed."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-3343
